@startuml
class ForgotPasswordModel {
    + ForgotPasswordModel(userManager:UserManager<User>, emailSender:IEmailSender)
    + <<async>> OnPostAsync() : Task<IActionResult>
}
class InputModel {
    + Email : string <<get>> <<set>>
}
PageModel <|-- ForgotPasswordModel
ForgotPasswordModel --> "Input" InputModel
ForgotPasswordModel +-- InputModel
@enduml
